import Head from "next/head"
import { useGame } from "../context/GameContextProvider"
import City from "../components/City"
import Timer from "../components/Timer"
import { AnimatePresence, motion } from "framer-motion"
import { useEffect, useState } from "react"

export default function Home() {
  const { score, maxScore, randomCity, randomCity2 } = useGame()
  const [animate, setAnimate] = useState(true)

  useEffect(() => {}, [randomCity, animate])

  return (
    <div className='h-screen bg-gray-800'>
      <Head>
        <title>Countries</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='space-y-4 border-b text-white'>
        <h1 className='py-5 text-center text-3xl'>Guess the population</h1>
        <div className='flex justify-evenly py-2'>
          <h2>Score: {score}</h2>
          <Timer />
          <h3>Max Streak: {maxScore}</h3>
        </div>
      </header>
      <AnimatePresence>
        <main className='mx-auto flex flex-col divide-y-2 overflow-hidden  text-5xl md:flex-row md:divide-x-2 md:divide-y-0'>
          <City
            key={randomCity.fields.country_code}
            cityName={randomCity.fields.name}
            countryCode={randomCity.fields.country_code}
            population={randomCity.fields.population}
          />
          <City
            key={randomCity2.fields.country_code}
            cityName={randomCity2.fields.name}
            countryCode={randomCity2.fields.country_code}
            population={randomCity2.fields.population}
            showPopulation={false}
          />
        </main>
      </AnimatePresence>
    </div>
  )
}
